Improved monster movement and spawning is now in seperate class
PKrystian/FiveNightsEscape pull request #25
Opened 2024-01-17 22:08 UTC by MBigaj

MapsActivity.kt:
	Removed spawning from  initial activity and moved to seperate
	class

Player now includes the text view for healthbar

2024-01-17 23:17 UTC, PKrystian requested changes
Found 2 big issues:

- Having less than 0 health doesn't end the game ( return to menu ).
-  One 'attack' from monster changes player health to '-1':
![Screenshot 2024-01-18 001147](https://github.com/PKrystian/FiveNightsEscape/assets/97467746/449fd415-50fd-49f1-8049-6ce8d2910d19)

If pull request didn't change/add these functionalities, create an issue/bugfix about them, if not try to fix it.

And other small issues in review comments.

2024-01-17 23:17 UTC, PKrystian commented on app/src/main/java/com/example/fivenightsescape/MapsActivity.kt
>                  currentPlayerLocation?.let { location ->
Parameter 'location' is never used, could be renamed to _

2024-01-17 23:17 UTC, PKrystian commented on app/src/main/java/com/example/fivenightsescape/monster/MonsterSpawner.kt
> +        when (monsterType) {
Code repetition in spawnMonster – can we reduce redundancy for clarity?
Differences in types are MonsterStanding, Moving, Wandering in `this.monsterController.addMonster(xxxxxxx`, everything else is repeating.
Like something similar to addMonster method.
```kt
when (this.difficulty) {
  DIFFICULTY_EASY -> spawnMonsterForDifficulty(dice, EASY_SPAWNER_BASIC, EASY_SPAWNER_MODIFIER)
  DIFFICULTY_MEDIUM -> spawnMonsterForDifficulty(dice, MEDIUM_SPAWNER_BASIC, MEDIUM_SPAWNER_MODIFIER)
  DIFFICULTY_HARD -> spawnMonsterForDifficulty(dice, HARD_SPAWNER_BASIC, HARD_SPAWNER_MODIFIER)
  else -> {
    // do some log error
  }
}
```

2024-01-17 23:17 UTC, PKrystian commented on app/src/main/java/com/example/fivenightsescape/player/Player.kt
> +        this.healthBar.text = this.health.toString()
Should be: (for both / one below)
```kt
"Health: " + this.health.toString()
```
as user won't know what numbers stand for.
![Screenshot 2024-01-18 001035](https://github.com/PKrystian/FiveNightsEscape/assets/97467746/90c8dcad-1555-44d7-bc7c-e09354705e41)

2024-01-17 23:17 UTC, PKrystian commented on app/src/main/java/com/example/fivenightsescape/player/Player.kt
> +class Player(var position: LatLng, val healthBar: TextView): ViewModel() {
This field leaks a context object.
You can fix it by changing it to:
```kt
class Player(var position: LatLng, healthBar: TextView) : ViewModel() {
  private var health: Int = PLAYER_HEALTH // This line stays the same
  private val healthBarRef: WeakReference<TextView> = WeakReference(healthBar)
  private val healthBar: TextView?
  get() = healthBarRef.get()
```
add `?` to both `this.healthBar.text = this.health.toString()`:
```kt
this.healthBar?.text = this.health.toString()
```

2024-01-18 16:09 UTC, MBigaj commented on app/src/main/java/com/example/fivenightsescape/monster/MonsterSpawner.kt
> +        when (monsterType) {
Unfortunately it's impossible with how it is constructed now, we have to initialize monsters with their respective types, cannot create constructor builder

2024-01-18 16:41 UTC, PKrystian approved these changes
GJ!

2024-01-18 16:42 UTC, merged